### ISSUE TITLE
Fusermount unmount sometimes fails

### ISSUE THREAD

**Issue by adamtheturtle** [msh100/ACDTools#41]
I noticed that most of my media was not visible in Plex.

I ran `/home/ACDTools/acdtools mount`.
I saw:

```
[2017-03-27 15:55:38] [INFO ] Unmounting /home/.mounts/acd-decrypted/
fusermount: failed to unmount /home/.mounts/acd-decrypted: Device or resource busy
```

I searched for this issue and found and used `umount -l /home/.mounts/acd-decrypted/`.

This worked and I then ran `/home/ACDTools/acdtools mount` and all seems fine.

Suggestion - and I fully admit I don't know the full consequences of this - replace `fusermount -u` with `umount -l`.

**Comment by msh100** [comment]
Lazy unmounting will kill open file handles which could maybe cause problems if you're writing?

I guess the unmount command could at least give a bit more insight as to what processes are using the mountpoint rather than that pretty ugly error.
